version: 2
working_directory: ~/project
jobs:
  build:
    docker:
      - image: debian:stretch
    
    steps:
      - checkout
      - run: 
        name: install hasura cli
        command: 
          wget https://github.com/hasura/graphql-engine/releases/download/v1.0.0-beta.4/cli-hasura-darwin-amd64
          curl -L# -o /bin/hasura https://github.com/hasura/graphql-engine/releases/download/v1.0.0-beta.4/cli-hasura-darwin-amd64
          chmod +x /bin/hasura 

      - run: 
        name: apply migrations
        command: |
          cd ../
          hasura migrate apply --endpoint "HASURA_ENDPOINT" # --admin-secret "$HASURA_ADMIN_SECRET"
